### ISSUE TITLE
feature-udp.md / Transfer protocol over UDP の翻訳

### ISSUE THREAD

**Issue by cahlchang** [mohikanz/http3-explained#21]

**Comment by ebiiim** [comment]
#12

**Comment by inductor** [comment]
https://github.com/mohikanz/http3-explained/pull/76/files#diff-8f84da5b176cee1cc0d3be07ab0da78cL3
Upstreamの更新を取り込んだので必要があれば再度PR投げてください

確認作業は必要だと思うので一旦Reopenします。（不要であればCloseしてください）
