### ISSUE TITLE
proc-ietf.md / IETF の翻訳

### ISSUE THREAD

**Issue by cahlchang** [mohikanz/http3-explained#29]

**Comment by hidesuke** [comment]
PR 作成済 https://github.com/inductor/http3-explained/pull/1

**Comment by inductor** [comment]
https://github.com/mohikanz/http3-explained/pull/76/files#diff-0b5f853ddfb80adf2baaeeb3e0e06695R26
Upstreamの更新を取り込んだので必要があれば再度PR投げてください

確認作業は必要だと思うので一旦Reopenします。（不要であればCloseしてください）

**Comment by hidesuke** [comment]
確認しました。英語の改善のみで、内容が変わるような変更はなかったので、クローズします。
