### ISSUE TITLE
proc-status.md / Status の翻訳

### ISSUE THREAD

**Issue by cahlchang** [mohikanz/http3-explained#30]

**Comment by hidesuke** [comment]
PR作成済 https://github.com/inductor/http3-explained/pull/1

**Comment by inductor** [comment]
https://github.com/mohikanz/http3-explained/pull/76/files#diff-8d0ce44d4acf57e2719db0b9914b8fe6L6
Upstreamの更新を取り込んだので必要があれば再度PR投げてください

確認作業は必要だと思うので一旦Reopenします。（不要であればCloseしてください）

**Comment by hidesuke** [comment]
確認しました。英語の改善のみで、内容が変わるような変更はなかったので、クローズします。
