### ISSUE TITLE
quic-tls.md / Connections use TLS の翻訳

### ISSUE THREAD

**Issue by cahlchang** [mohikanz/http3-explained#37]

**Comment by kousukekikuchi1984** [comment]
一旦やってみますわ。

**Comment by kousukekikuchi1984** [comment]
done

**Comment by inductor** [comment]
https://github.com/mohikanz/http3-explained/pull/76/files#diff-451fb589107ea29f0c72b5b31bb78d62L4
Upstreamの更新を取り込んだので必要があれば再度PR投げてください

確認作業は必要だと思うので一旦Reopenします。（不要であればCloseしてください）

**Comment by kousukekikuchi1984** [comment]
全体に見直す必要があり。

**Comment by kousukekikuchi1984** [comment]
Done
