### ISSUE TITLE
quic-v2.md / QUIC v2 の翻訳

### ISSUE THREAD

**Issue by cahlchang** [mohikanz/http3-explained#39]

**Comment by misato8310** [comment]
[quic-v2.md](https://github.com/mohikanz/http3-explained/blob/add/japanese/ja/quic-v2.md) やってみます

**Comment by misato8310** [comment]
平日の日中は時間取れないので今週日曜日(2018/12/02)までに対応します

**Comment by inductor** [comment]
日曜までに対応ってなるとレビュー含めまた平日まるまる空いちゃうんで、できれば土曜には一時的な成果物があると良いなと思うんですが、難しそう？

分量的には翻訳つかいつつなら2時間もあれば終わると思う

**Comment by misato8310** [comment]
承知した！今晩頑張るので明日まで時間ください

**Comment by OldBigBuddha** [comment]
Merged #81
