### ISSUE TITLE
h3.mdの翻訳

### ISSUE THREAD

**Issue by beagleworks** [mohikanz/http3-explained#4]
紛らわしいので一旦delete

**Comment by beagleworks** [comment]
issueお疲れ様です
現状に沿った形にタイトル変更しておきます。

**Comment by inductor** [comment]
https://github.com/mohikanz/http3-explained/pull/76/files#diff-0b5f853ddfb80adf2baaeeb3e0e06695R26
Upstreamの更新を取り込んだので必要があれば再度PR投げてください

確認作業は必要だと思うので一旦Reopenします。（不要であればCloseしてください）
