### ISSUE TITLE
quic.md / How QUIC works の翻訳

### ISSUE THREAD

**Issue by cahlchang** [mohikanz/http3-explained#40]

**Comment by kousukekikuchi1984** [comment]
やります。

**Comment by kousukekikuchi1984** [comment]
やっぱしつらいかも

**Comment by akihirok2k2** [comment]
I do this! !

**Comment by inductor** [comment]
https://github.com/mohikanz/http3-explained/pull/76/files#diff-1c208c580c97f42dfcf998d907b4ec83L3
Upstreamの更新を取り込んだので必要があれば再度PR投げてください

確認作業は必要だと思うので一旦Reopenします。（不要であればCloseしてください

**Comment by akihirok2k2** [comment]
確認しました。大きな変更は内容に思いますのでCloseします。
